### ISSUE TITLE
cannot handle skipping Huffman scenario

### ISSUE THREAD

**Issue by jtian0** [szcompressor/cuSZ#17]
As of https://github.com/szcompressor/cuSZ/commit/20d4bb3b9c3397a30e01d804479a4fe41474acc3,
```
> ./bin/cusz -f32 -m r2r -e 1.0e-4.0 -i ~/Parihaka_PSTM_far_stack.f32 -D parihaka -z --skip huffman
[info] datum:           /path/to/Parihaka_PSTM_far_stack.f32 (4850339584 bytes) of type f32
[dbg]  original len:    1212584896 (padding: 34823)
[dbg]  Time loading data:       3.21981s
[info] quant.cap:       1024    input eb:       0.0001
[dbg]  Time inspecting data range:      0.0232671s
[info] eb change:       (input eb) x 12342.2 (rng) = 1.23422 (relative-to-range)
[dbg]  2-byte quant type, 4-byte internal Huff type

[info] Commencing compression...
[info] nnz.outlier:     16607   (0.00136955%)
[info] Compression finished, saved quant.code (Huffman skipped).

tar: Parihaka_PSTM_far_stack.f32.hbyte: Cannot stat: No such file or directory
tar: Parihaka_PSTM_far_stack.f32.canon: Cannot stat: No such file or directory
tar: Parihaka_PSTM_far_stack.f32.hmeta: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
[info] Written to:      /path/to/Parihaka_PSTM_far_stack.f32.sz
```
By giving `--skip huffman`, tar throws errors.

p.s. parihaka is a new test case that is added in https://github.com/szcompressor/cuSZ/commit/90b521b30925e42ede5a635111b123f6238b0e0e ahead of current https://github.com/szcompressor/cuSZ/commit/20d4bb3b9c3397a30e01d804479a4fe41474acc3

**Comment by dingwentao** [comment]
Hi @wenyugai can you look into this issue using "--skip huffman"? I think this is not difficult to address, please add an if-else branch to determine which files to include in the tar file.

**Comment by jtian0** [comment]
@wenyugai 
```bash
cusz -f32 -m r2r -e 1e-4 -i ./data/sample-cesm-CLDHGH -D cesm -z -x
```
Please also test this case, in which we put `-z` and `-x` altogether. If it's not instantaneously workable, please notify and we simply delete this case in all documents for now.

**Comment by wenyugai** [comment]
@jtian0 
I fixed the problem. Now -z and -x could be put together in on command.

**Comment by jtian0** [comment]
Thanks @wenyugai; this issue is resolved in https://github.com/szcompressor/cuSZ/commit/48fe47cd88c6842e77efcb872ff29a3044f32e37.
