### ISSUE TITLE
CUDA API failed at src/cusz.cu:154 with error: initialization error (3)

### ISSUE THREAD

**Issue by mawpolaris** [szcompressor/cuSZ#43]
Hi,

I got an error message:
"CUDA API failed at src/cusz.cu:154 with error: initialization error (3)"
when I tried running the examle:
./bin/cusz -t f32 -m r2r -e 1e-4 -i ./data/ex-cesm-CLDHGH -D cesm -z

Could someone please help on this?

**Comment by dingwentao** [comment]
Hi @mawpolaris,

It looks like this is not an issue from cuSZ code, but an issue of CUDA driver configuration. Did you try "nvidia-smi" to check your Nvidia GPU device and run a sample GPU code? If not, you should first try to run some sample CUDA code and ensure your CUDA device/environment is configured successfully. Below is the output I just got from my side with A100 GPU and CUDA11. 

$ nvidia-smi
Tue May 11 09:03:43 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-PCIE-40GB      Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   29C    P0    32W / 250W |      0MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-PCIE-40GB      Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   31C    P0    34W / 250W |      0MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ ./bin/cusz -t f32 -m r2r -e 1e-4 -i ./data/ex-cesm-CLDHGH -D cesm -z
info  load ./data/ex-cesm-CLDHGH 25920000 bytes, f32 ..................... [ok]
 dbg  add padding: 2546 units
 dbg  time loading datum: 2.42934 sec
 dbg  time scanning: 0.000803619 sec
 dbg  2-byte quant type, 4-byte internal Huff type
info  invoke lossy-construction .......................................... [ok]
info  nnz/#outlier: 21024 (0.324444%) saved .............................. [ok]
 dbg  Huffman chunk size: 256 thread num: 25313
 dbg  to store Huffman encoded quant.code (default)
 dbg  time tar'ing: 0.780108 sec
info  output: ./data/ex-cesm-CLDHGH.sz ................................... [ok]

Let me know if this helps. 

Thanks,
Dingwen

**Comment by mawpolaris** [comment]
Hi Dingwen, 

Thank you for your reply.

Here is what I got. 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+

1. How to enable cuda driver?
2. Do I need to upgrade nvidia-smi version to 450.80.02?
