### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by shauryapatel1995** [szcompressor/cuSZ#5]
Hi team, 
I had a couple of questions for the project. I am trying to do a study and wanted to consider your project in that. 

1. When are you planning to decouple the compression and decompression algorithms?
2. Do you expose an API/Kernel I can use for compression and decompression or is it just the command?
3. Can we only save the results to files? I imagine it should not be an issue to store it on an actual memory instead of a file. 

Looking forward to you answers!

**Comment by robertu94** [comment]
I don't know what the plans are for cuSZ, but all of these features are required to support [libpressio](https://github.com/CodarCode/libpressio) as well.

**Comment by dingwentao** [comment]
> Hi team,
> I had a couple of questions for the project. I am trying to do a study and wanted to consider your project in that.
> 
> 1. When are you planning to decouple the compression and decompression algorithms?
> 2. Do you expose an API/Kernel I can use for compression and decompression or is it just the command?
> 3. Can we only save the results to files? I imagine it should not be an issue to store it on an actual memory instead of a file.
> 
> Looking forward to you answers!

Thanks, @shauryapatel1995 for contacting us. 

For your questions:
1. Our next release v0.2 will have this decoupled compression and decompression. We target to release it in early October. 
2. Yes, this is also our target. We need to write a wrapper API for this. I would say it will be in the release of v0.2.x.
3. You're right, it's definitely not necessary to save all the compressed results in the file. Actually, after we provide the API, this won't be an issue. 

Please test cuSZ to first understand the compression quality and throughput on your datasets. We are actively developing these features which will released by the end of October. 

Thanks,
Dingwen

**Comment by shauryapatel1995** [comment]
Hi @dingwentao thanks for your response. Looking forward to the enhancements, till then I will use the current version and see what I can work with.

**Comment by dingwentao** [comment]
Hi @shauryapatel1995 cuSZ [v0.1.1](https://github.com/szcompressor/cuSZ/releases/tag/v0.1.1) has been released. Please check it out. Compression and decompression have been been decoupled. Let us know if it works good for you.

**Comment by shauryapatel1995** [comment]
Hi @dingwentao I am working on the study as we speak! Thanks for the update, looking forward to the other features later as well.

**Comment by mawpolaris** [comment]
Hi @dingwentao, has API/Kernel been available in the current version?

**Comment by jtian0** [comment]
Hi @mawpolaris, we have largely (and internally) repurposed and refactored our project since this issued is opened. Currently, we have almost finished kernels and are working on the driver program/high-level APIs.

**Comment by jtian0** [comment]
The document is moved to [wiki](https://github.com/szcompressor/cuSZ/wiki); would reopen if there is any follow-up.
