### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by pythonmobile** [szcompressor/cuSZ#63]
On a A10 machine: I could not build using ./build.py ampere. So I compiled it using ./build.py turing. 

(With -e 1e-4, 1e-5 it worked)

```
time ./bin/cusz -t f32 -m abs -e 1e-6 -i ./data/randompatch.bin.npy -l 256,256 -z --report time
  ::  load ./data/randompatch.bin.npy 262144 bytes                         [ok]
  ::  compressing...                                                       [ok]
  ::  #outlier =  65409 (99.806213%)                                       [ok]
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 1st step: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)

real	0m0.570s
user	0m0.261s
sys	0m0.138s
```

**Comment by jtian0** [comment]
Hi @pythonmobile,

https://github.com/szcompressor/cuSZ/commit/f5cfd0cfe40c3056ae1b00083531559aff9357e8 should fix the compilation issue, `./build.py ampere`.
https://github.com/szcompressor/cuSZ/commit/f7603289e25f30168e34d5409edcd18f8c26e758 may fix the second issue: the default out-of-range outlier density now can be overridden. As the error bound goes small, outliers may exceed the default allocated space, 5% of the input length. The density is in 0-1 range; by overriding, please append, e.g., `--config density=0.2`.

Right now, it's not ready to merge the updates to major branches. Please use the below for your testing.
```bash
git clone https://github.com/szcompressor/cuSZ.git cusz-test && cd cusz-test
git checkout -b canary 13f37ba

./bin/cusz -t f32 -m abs -e 1e-6 -i ./data/randompatch.bin.npy -l 256,256 --config density=0.2 -z --report time
```

**Comment by pythonmobile** [comment]
```
./bin/cusz -t f32 -m abs -e 1e-6 -i ./data/randompatch.bin.npy -l 256,256 --config density=0.2 -z --report time
  ::  load ./data/randompatch.bin.npy 262144 bytes                         [ok]
  ::  compressing...                                                       [ok]
  ::  #outlier =  65409 (99.806213%)                                       [ok]
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 1st step: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)
```

Also the only way I can compile the code is using "./build.py turing debug" - while I am on the a10 GPU. Specs: ```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   29C    P8     9W / 300W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+```

**Comment by jtian0** [comment]
Hi @pythonmobile,

As of CUDA 11.2, everyhing seems opaque, as multiple factors can affect the program run, namely
- system architecture, system enviroment
- cmake, gcc
- CUDA version, driver version
- the installation source of CUDA SDK (e.g., the toolchain from `nvhpc` suite may be tricky as I tested.)

I may need more information to understand the status. Would mind sharing more information? If so, please try the [script](https://github.com/szcompressor/cuSZ/blob/robust/exp/script/py.diagnostics) by

```bash
git clone -b robust/exp https://github.com/szcompressor/cuSZ.git cusz-diagnostics
cd cusz-diagnostics/script
python3 py.diagnostics  ## or `python py.diagnostics`

```

The script output a file named `cusz-checkenv-<datetime>.txt`. Please attach the output in this thread or send the output to [_tian.jn+dev 'at' gmail.com_]. (Note that part of the output is anomynized, if you have extra concern, please feel free to modify the output.)

In addition, I have concern of the data you tested. For example, the size (in you case it is pretty small) may trigger some unknown bug.) Would you mind sharing some openly accessible data? Alternatively, please consider sending the sample data to [_tian.jn+dev 'at' gmail.com_]. If neither is okay, please consider using this [miniprogram](https://github.com/szcompressor/cuSZ/blob/robust/exp/stat/exp_percentile100.cc) to gather the percentile information such that I can test with synthetic data.
```bash
## branch `robust/exp`
cd cusz-diagnostics/stat
make percentile ## and in your case
./exp_percentile100 <path to>/randompatch.bin.npy $(echo "256 * 256" | bc) host
```
In addition, this miniprogram uses `thrust`, please also try if `thrust` works on device.
```bash
./exp_percentile100 <path to>/randompatch.bin.npy $(echo "256 * 256" | bc) device
```

Thank you.

**Comment by pythonmobile** [comment]
@jtian0  - I will get you the dataset soon.

- CPU model:	AMD EPYC 7R32
- byte order:	Little Endian

NVIDIA A10G, 22731 MiB, Ampere

- LD_LIBRARY_PATH:	- PATH:

- found cmake:
	cmake version 3.22.0
	<some user>/.local/bin/cmake
- found nvcc:
	Cuda compilation tools, release 10.1, V10.1.243
	/usr/bin/nvcc
- found driver:
	NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5
	/usr/bin/nvidia-smi
- found gcc:
	gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
	/usr/bin/gcc
- !! could not find clang.

**Comment by jtian0** [comment]
@pythonmobile The `nvcc` line draws my attention: Ampere GPUs work with CUDA 11.x. I assume that you are using some package manager (e.g., [spack](https://spack.io), and/or [module](https://modules.readthedocs.io/en/latest/module.html)), with multiple versions of CUDA sdks installed.

The diagnostics script (as if it's the current shell) detects the default binary while `cmake` may detect differently. (Or may not, I admit that's cursively written.) Can you manage to load CUDA 11.5? e.g., `module load cuda/11.5.[0|1]`, `spack load cuda`. That's corresponding to your driver version (495).

**Comment by jtian0** [comment]
@pythonmobile The memory related issue may not be in situ but propagated in the later compression stages. I fixed several issues when refactoring. Please check out the updated release.

**Comment by jtian0** [comment]
Would reopen if there is any follow-up.
