### ISSUE TITLE
cmake --install . does not work

### ISSUE THREAD

**Issue by vicentebolea** [szcompressor/cuSZ#65]
The generate Makefile/ninja.rules does not have any install rule. While I understand that cuSZ comes with the build.py script, this makes things complicated when trying to use SZ from other CMake projects.

**Comment by jtian0** [comment]
Hi @vicentebolea, 

Thank you for pointing out, and I will improve: I left out the installation. 

The intention of `build.py` is to avoid lengthy commands when invoking `cmake` or extra configuration in `CMakeLists.txt` regarding CUDA arch. But I agree that the script should not be a trouble when interoperating with `cmake`.

**Comment by vicentebolea** [comment]
I could also possibly help cmakefying this

**Comment by Zhang690683220** [comment]
Hi,

I'm also experiencing this cmake install issue. By the way, is it possible to build shared libraries? Some CRAY supercomputers doesn't have good support to static linkage.

Bests,

Bo

**Comment by jtian0** [comment]
Hello @Zhang690683220,

We have a new branch where shared libraries are enabled. The branch sees building process problems because of the dependency modules (such as NVIDIA::CUB). Can you tell which CUDA version are you using? I might come up with a quick fix (by dropping compatibility).

CC: @dingwentao

**Comment by Zhang690683220** [comment]
> 

Hi,

I'm using cuda/11.5 and maybe upgrade to 11.7 later. If you have the access to perlmutter, can you do a test on it? Because the math library like cublas and other stuffs are strangely managed on that machine.

Bo

**Comment by jtian0** [comment]
Hi @Zhang690683220, we just released a new version, [v0.3.1](https://github.com/szcompressor/cuSZ/releases/tag/v0.3.1), corresponding to https://github.com/szcompressor/cuSZ/commit/4f9c9f162d5b34e9a5dbdd87d6cfcae7b8f6037e. 

It is dynamically linked by default
https://github.com/szcompressor/cuSZ/blob/4f9c9f162d5b34e9a5dbdd87d6cfcae7b8f6037e/CMakeLists.txt#L6
We tested on Perlmutter with the following modules loaded
```
module load cmake/3.22.0
module load gcc/10.3.0
module load cudatoolkit/11.5
```
And it works in our initial test. 

Please refer to the document to [build from the source code](https://github.com/szcompressor/cuSZ/wiki/Build-and-Install). If you have any questions, please tell us. Thank you for trying out our software.

**Comment by jtian0** [comment]
Hi @vicentebolea, I am sorry for the late reply. 
We spent months resolving most compiling issues. We currently have full support for `cmake` compiling, and the previous `build.py` is retired. 

Thank you for reaching out to help! We appreciate it.

**Comment by vicentebolea** [comment]
@jtian0 great! Thanks for help, this was a long waited feature.
