### ISSUE TITLE
Building a standalone example

### ISSUE THREAD

**Issue by maltempi** [szcompressor/cuSZ#71]
Hello everybody, I cloned the newest code release from main branch and now I want to build a standalone example, separately from cusz build.

First: I'm building cusz following the [documentation](https://github.com/szcompressor/cuSZ/wiki/Build-and-Install). I'm replacing `[/path/to/install/dir]` by `/opt/cusz`. This step is pretty straight forward I'm doing `cmake {params} -> make  -j8 -> make install`.

Then I just copied this [example](https://github.com/szcompressor/cuSZ/blob/1dd0b8ae265daf88be2a6be1c4152e4bf83a0a99/example/src/capi.cu) to a different folder (for example, standalone_example/src) and created a CMakeLists.txt file -- its source code can be found in [this gist](https://gist.github.com/maltempi/0d35fc74b1521eb963fb19c0fb2c1da6).

Having this structure created, I build my standalone example and try to execute it:
```
mkdir build && cd build
cmake ..
make

./ex-api ${cesm-CLDHGH-3600x1800}
```

I'm having this error:
```
root@c5dd7f9907f7:/cusz/my_example/build# ./ex-api ../../cesm-CLDHGH-3600x1800
peeking uncompressed data, 20 elements
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorUnsupportedPtxVersion: the provided PTX was compiled with an unsupported toolchain.
Aborted
```

Sometimes I'm getting segmentation fault.
```
root@c5dd7f9907f7:/cusz/my_example/build# ./ex-api ../../cesm-CLDHGH-3600x1800
peeking uncompressed data, 20 elements
Segmentation fault
```

Curiously, when I run the same example from the cusz build folder (`build/example/capi`) it works well. I'm suspecting something is wrong in my CMakeLists.txt but I'm not finding what could be.  Note: I'm building my standalone example in the same machine I'm building cusz (my machine can be found on [docker hub](https://hub.docker.com/r/maltempi/cusz-dev-build))

Any thoughts about that?

Thank you very much in advance.

**Comment by jtian0** [comment]
@maltempi Sorry for the late response. `thrust` is known to cause trouble periodically because of the compiler requirement, and I am actively making changes in `canary-*` to address build-related issues. Right now, I have some difficulty pulling your docker environment, could you give a try on `canary-3` branch (will merge to `canary` then `develop`), based on which we can create an example? The snippet is listed below.

1. build
```bash
# in [cusz-src]/build (build without specifying the installation path for a quick test)
cmake .. && make -j
```
2. create an example by moving `[cusz-src]/example/src/capi.cu` to a new dir `[cusz-example]`
```bash
# CMakeLists.txt in [cusz-example]
> $ ls
build  capi.cu  CMakeLists.txt
```
2.1 `CMakeLists.txt`

```
# The goal is to create an equivalence to
# nvcc capi.cu -L[cusz-src]/build -lparszutils_g -lparszstat_g -lcusz -I[cusz-src]/include -o capi

cmake_minimum_required(VERSION 3.18)
project(CUSZ-example LANGUAGES CUDA CXX C)

find_package(CUDAToolkit REQUIRED)
include_directories([cusz-src]/include)

find_library(FOO_LIB parszstat_g)
find_library(BAR_LIB parszutils_g)
find_library(SUE_LIB cusz)

add_executable(capi capi.cu)
target_link_libraries(capi PRIVATE "${FOO_LIB}" "${BAR_LIB}" "${SUE_LIB}" CUDA::cudart CUDA::cuda_driver)
```

2.2 invoke cmake
```bash
cd build && cmake .. -DCMAKE_PREFIX_PATH=[cusz-src]/build && make
```

2.3 execute
```bash
LD_LIBRARY_PATH=[cusz-src]/build capi ${CESM}
```

Please let me know if there is any issue..

**Comment by maltempi** [comment]
I tested it in 2024 and it is working great! Closing the issue. Thank you very much, @jtian0 .
